name: skyrim_alchemy
description: Skyrim alchemy calculator.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  numberpicker: "^0.1.0"
  built_collection: ^3.0.0
  redux: ">=2.0.0 <3.0.0"
  rxdart: ^0.16.0+2
  flutter_redux: ">=0.3.0 <0.4.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true